# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Default configuration for use with tic package
# Usually you shouldn't need to change the first part of the file

# DO NOT CHANGE THE CODE BELOW
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libgsl0-dev bwidget
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install gcc
  - mkdir ~/.R
  - echo -e "CXXFLAGS = -Ofast -march=native -fpic -pipe -std=c++11\nMAKE = make -j8" > ~/.R/Makevars
  - R -q -e 'install.packages(c("remotes", "knitr", "rmarkdown", "tidyverse", "SDMTools", "bench")); remotes::install_github("ropenscilabs/tic"); remotes::install_github("ropensci/NLMR"); tic::prepare_all_stages(); remotes::install_deps(dependencies = TRUE); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'
# DO NOT CHANGE THE CODE ABOVE

# Custom parts:

# Header
language: r
sudo: true
dist: trusty
cache: packages
warnings_are_errors: false

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

notifications:
  email:
    recipients:
      - maximilian.hesselbarth@uni-goettingen.de
    on_success: always # default: change
    on_failure: always # default: always

#services
services:
